version: '3.9'
services:
  redis:
    container_name: redis_container
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    environment:
      REDIS_ARGS: --save 20 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost


  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.0
    ports:
      - "9042:9042"
    restart: always
    environment:
      - SCYLLA_CLUSTER_NAME=scylla-docker
      - SCYLLA_DC=datacenter1
      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
      - SCYLLA_RPC_ADDRESS=0.0.0.0
      - SCYLLA_NUM_TOKENS=256
      - SCYLLA_AUTO_BOOTSTRAP=true
    command: --seeds=scylla-node1,scylla-node2 --memory 750M --api-address 0.0.0.0 --reactor-backend=epoll

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=watchlist'
      - 'POSTGRES_PASSWORD=2255'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'