server:
  port: 8080

spring:
  application:
    name: exchange-gateway
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8081}

  #Gateway Specific
  cloud:
    gateway:
      routes:
        #Service Registry
        - id: service-registry
          uri: lb://eureka-server
          filters:
            - SetPath=/
          predicates:
            - Path=/eureka

        - id: service-registry-static
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**


        #RiskManagement
        - id: risk-management
          uri: lb://risk-management
          predicates:
            - Path=/api/exchange/risk/**
            - Method=GET,PUT,POST,DELETE
          filters:
            - SecurityFilter


        #AuthService Client
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/bainsight/auth/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter


        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/bainsight/admin/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter


        #Market Update
        - id: market-update
          uri: lb://market-update
          predicates:
            - Path=/ws
            - Method=GET,PUT,POST


        #Watchlist
        - id: watchlist-service
          uri: lb://watchlist-service
          predicates:
            - Path=/api/bainsight/watchlist/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter


        #History
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/api/bainsight/history/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter


        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/bainsight/portfolio/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter

        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/bainsight/wallet/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter

        - id: order-persistence
          uri: lb://order-persistence
          predicates:
            - Path=/api/bainsight/persistence/**
            - Method=GET
          filters:
            - SecurityFilter


        - id: order-processing
          uri: lb://order-processing
          predicates:
            - Path=/api/bainsight/order/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter

        - id: risk-management
          uri: lb://risk-management
          predicates:
            - Path=/api/bainsight/risk/**
            - Method=GET,POST
          filters:
            - SecurityFilter



#LOGGING
#logging:
#  level:
#    root: info
#    org:
#      springframework:
#        security: ${LOGGING_LEVEL:debug}
#        cloud:
#          gateway: trace
#          route:
#            RouteDefinitionLocator:

rsa:
  private-key: /certs/private.pem
  public-key: /certs/public.pem

allowed:
  origin: ${ALLOWED_ORIGIN:http://localhost:4200}
