server:
  port: 8080

spring:
  application:
    name: exchange-gateway
  config:
    import: optional:configserver:http://localhost:8888

  #Gateway Specific
  cloud:
    gateway:
      routes:
        #Data Registry
        - id: service-registry
          uri: http://localhost:8761
          filters:
            - SetPath=/
          predicates:
            - Path=/eureka

        - id: service-registry-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        #RiskManagement
        - id: risk-management
          uri: lb://risk-management
          predicates:
            - Path=/api/exchange/risk/**
            - Method=GET,PUT,POST,DELETE
          filters:
            - HeaderManipulationFilter

        #AuthService Client
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/bainsight/auth/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/bainsight/admin/**
            - Method=GET,PUT,POST
          filters:
            - SecurityFilter

        #Market Update Data
        - id: market-update
          uri: lb://market-update
          predicates:
            - Path=/ws
            - Method=GET,PUT,POST


# TODO:Move to config server

#LOGGING
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
        cloud:
          gateway: trace
          route:
            RouteDefinitionLocator: info

rsa:
  private-key: file:/Users/apple/Desktop/BAINSIGHT_API/YLibrary/src/main/resources/certs/private.pem
  public-key: file:/Users/apple/Desktop/BAINSIGHT_API/YLibrary/src/main/resources/certs/public.pem

allowed:
  origin: http://localhost:4200