apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: nivedsuresh/config-server:1.0.0
        name: configserver
        ports:
          - containerPort: 8081
        resources: {}
        imagePullPolicy: IfNotPresent
        env:
          - name: GIT_ACCESS_TOKEN
            valueFrom:
              configMapKeyRef:
                key: config_server_git_password
                name: common-config
          - name: GIT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: config_server_git_username
                name: common-config

---

apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081