
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator
  labels:
    app: data-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-aggregator
  template:
    metadata:
      labels:
        app: data-aggregator
    spec:
      containers:
        - name: data-aggregator
          image: nivedsuresh/data-aggregator:1.0.6
          ports:
            - containerPort: 8084
              protocol: TCP
            - containerPort: 40456
              protocol: UDP
          env:
            - name: SPRING_APPLICATION_PORT
              value: "8084"
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8081'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev,test,sim'
            - name: KAFKA_BOOTSTRAP_SERVER
              value: 'broker:29092'
            - name: USER_SERVICE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: aeron_user_service_channel
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: common_redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bainsight-secrets
                  key: common_redis_password

---
apiVersion: v1
kind: Service
metadata:
  name: data-aggregator
spec:
  selector:
    app: data-aggregator
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: tcp
    - protocol: UDP
      port: 40456
      targetPort: 40456
      name: udp
