apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: bainsight-ns
  name: allow-udp
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: UDP
          port: 40456
  egress:
    - ports:
        - protocol: UDP
          port: 40456