CREATE TABLE orders
(
    order_id            UUID NOT NULL,
    ucc                 UUID,
    symbol              VARCHAR(255),
    exchange            VARCHAR(255),
    transaction_type    VARCHAR(255),
    order_type          VARCHAR(255),
    quantity_requested  BIGINT,
    price_requested_for DOUBLE PRECISION,
    total_amount_spent  DOUBLE PRECISION,
    quantity_matched    BIGINT DEFAULT 0,
    order_placed_at     TIMESTAMP WITHOUT TIME ZONE,
    last_updated_at     TIMESTAMP WITHOUT TIME ZONE,
    order_status        VARCHAR(255),
    version             BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE INDEX idx_order_order_placed_at ON orders (order_placed_at);

CREATE INDEX idx_order_ucc ON orders (ucc);


CREATE TABLE match
(
    match_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id          UUID,
    match_time        TIMESTAMP WITHOUT TIME ZONE,
    matched_quantity  BIGINT                                  NOT NULL,
    price_matched_for DOUBLE PRECISION                        NOT NULL,
    was_validated     BOOLEAN                                 NOT NULL,
    match_status      VARCHAR(255),
    CONSTRAINT pk_match PRIMARY KEY (match_id)
);